name: Lighthouse

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.11.0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile && npm install -g @lhci/cli@0.8.x
      - run: |
          cd ./apps/site
      - name: Run lighthouse
        run: lhci autorun
